[Feature] Add template and voter login component
Enye-Team-Giraffe/vote-right-frontend pull request #5
Opened 2019-11-27 19:24 UTC by usmanoa

### What does this PR do?
- This PR adds a default template and voter login form

#### Description of Task to be completed?
- Add reusable template and voter login component

#### Checklist:
- [x] Add default template
- [x] Add voter login component
- [x] Add voter input validation

2019-11-27 19:30 UTC, xand6r approved these changes
Looks good, I appreciate your Javascript comments. Please try to do the same for the html so  we can add functions to it without reading it too much. Cheers

2019-11-27 19:32 UTC, Way2nnadi commented
@usmanoa travis is failing, make sure to look at the what is causing the failure and fix it

2019-11-27 19:33 UTC, Way2nnadi commented on src/components/login/components/Login.js
> +    const handleChangeNin = ({ target }) => {
fix the indent here

2019-11-27 19:33 UTC, Way2nnadi commented on src/components/login/components/Login.js
> +    const handleChangePhoneNumber = ({ target }) => {
fix indent

2019-11-27 19:33 UTC, Onyimatics requested changes
Nice work @usmanoa. However, our build is failing, please try and fix it. Thank you.

2019-11-27 19:33 UTC, Xand6r commented on src/components/login/components/Login.js
> +    const handleChangePhoneNumber = ({ target }) => {
Thank you uche

2019-11-27 19:34 UTC, Way2nnadi commented on src/components/login/components/Login.js
> +                <Title className="form__heading" level={3}>Sign in to your Account</Title>
save string in `constants.js` file

2019-11-27 20:24 UTC, usmanoa commented on src/components/login/components/Login.js
> +                <Title className="form__heading" level={3}>Sign in to your Account</Title>
Thanks, I'll do that

2019-11-27 20:25 UTC, usmanoa commented on src/components/login/components/Login.js
> +    const handleChangeNin = ({ target }) => {
Thanks, I'll fix it.

2019-11-27 23:21 UTC, Onyimatics commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be able to login to voteright](https://trello.com/c/MKNnj7im/41-users-should-be-able-to-login-to-voteright)

2019-11-28 11:05 UTC, Onyimatics approved these changes
Well done @usmanoa  I can see the build is passing now.

2019-11-28 11:08 UTC, merged